version: '3.8'

services:
  api-service:
    build:
      context: ./api-service
      args:
        - BUILD_NUMBER=${BUILD_NUMBER:-local}
        - GIT_COMMIT=${GIT_COMMIT:-local}
    ports:
      - "4000:4000"
    networks:
      yossi-network:

  web-service:
    build:
      context: ./web-service
      args:
        - BUILD_NUMBER=${BUILD_NUMBER:-local}
        - GIT_COMMIT=${GIT_COMMIT:-local}
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api-service:4000/api/time
    networks:
      yossi-network:

networks:
  yossi-network:
    driver: bridge